steps:
  # Install Conda
  - name: 'gcr.io/cloud-builders/bash:v0.42.2'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Download and install Conda
        wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
        bash ~/miniconda.sh -b -p $_CUSTOM_HOME/conda
        export PATH="$_CUSTOM_HOME/conda/bin:$_CUSTOM_PATH"
        conda init bash
        source ~/.bashrc
    id: Install Conda
    env:
      - '_CUSTOM_HOME=/custom/path'

  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Akansh-Verma/CropXcel_gfg.git']
  # Create and activate Conda environment
  - name: 'gcr.io/agro-379806/conda'
    args: ['create', '-n', 'myenv', '--file', 'environment.txt']
    id: Create Conda environment
    volumes:
      - name: 'vol-conda'
        path: '/builder/conda'
  - name: 'gcr.io/agro-379806/conda'
    args: ['activate', 'myenv']
    id: Activate Conda environment
    volumes:
      - name: 'vol-conda'
        path: '/builder/conda'
  # Build and deploy the app
  - name: 'gcr.io/agro-379806/django'
    args: ['python', 'manage.py', 'collectstatic', '--noinput']
    id: Collect Static Files
  - name: 'gcr.io/agro-379806/django'
    args: ['python', 'manage.py', 'migrate']
    id: Apply Database Migrations
  - name: 'gcr.io/agro-379806/django'
    args: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    id: Start Django Server
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instances create-with-container instance-1 \
        --machine-type=n2d-standard-2 \
        --container-image=gcr.io/agro-379806/django \
        --container-privileged \
        --boot-disk-size=200GB \
        --tags=http-server \
        --zone=us-central1-a

  # Script to start and stop the instance after 5 minutes
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sleep 5m && gcloud compute instances stop instance-1 &
images: ['gcr.io/agro-379806/django']
timeout: 1800s
substitutions:
  _CUSTOM_PATH: /custom/path
  _CUSTOM_HOME: /builder/custom
